### ISSUE TITLE
Check if window.google.maps Already Exists Before Instantiating 

### ISSUE THREAD

**Issue by pacarvalho** [cedricdelpoux/react-google-maps-loader#43]
Would it be within the scope of this library to include an option to check if `window.google.maps` is already loaded before attempting to load it through the library? 

I have encountered this need in a large application where more than one module in distinct portions of it load Google Maps causing a conflict. We addressed it in our code. However, would it be an appropriate PR to add this functionality to this library?

![image](https://user-images.githubusercontent.com/860599/80288156-07e09880-8704-11ea-8612-86d9b87976be.png)

**Comment by cedricdelpoux** [comment]
Hi @pacarvalho could. you try the latest `4.3.0` and the issue is fixed?

**Comment by pacarvalho** [comment]
Hey @cedricdelpoux. I apologize for not including this in the opening statement. We are using version 4.2.6. Was the fix introduced between these versions?

**Comment by cedricdelpoux** [comment]
Yes, in the `4.3.0`
